# Generated by Django 4.0.2 on 2022-03-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_alter_todolist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user',
            new_name='author',
        ),
    ]
