# Generated by Django 4.0.3 on 2022-03-17 16:32

from django.conf import settings
from django.db import migrations, models
import nt


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=nt.truncate, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
